package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class Day implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.D_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.D_income
     *
     * @mbg.generated
     */
    private Double dIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.D_expend
     *
     * @mbg.generated
     */
    private Double dExpend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day.D_profit
     *
     * @mbg.generated
     */
    private Double dProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.D_id
     *
     * @return the value of day.D_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.D_id
     *
     * @param dId the value for day.D_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.D_income
     *
     * @return the value of day.D_income
     *
     * @mbg.generated
     */
    public Double getdIncome() {
        return dIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.D_income
     *
     * @param dIncome the value for day.D_income
     *
     * @mbg.generated
     */
    public void setdIncome(Double dIncome) {
        this.dIncome = dIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.D_expend
     *
     * @return the value of day.D_expend
     *
     * @mbg.generated
     */
    public Double getdExpend() {
        return dExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.D_expend
     *
     * @param dExpend the value for day.D_expend
     *
     * @mbg.generated
     */
    public void setdExpend(Double dExpend) {
        this.dExpend = dExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day.D_profit
     *
     * @return the value of day.D_profit
     *
     * @mbg.generated
     */
    public Double getdProfit() {
        return dProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day.D_profit
     *
     * @param dProfit the value for day.D_profit
     *
     * @mbg.generated
     */
    public void setdProfit(Double dProfit) {
        this.dProfit = dProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dId=").append(dId);
        sb.append(", dIncome=").append(dIncome);
        sb.append(", dExpend=").append(dExpend);
        sb.append(", dProfit=").append(dProfit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}