package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class DayMp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.DP_id
     *
     * @mbg.generated
     */
    private Integer dpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.C_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.DMP_num
     *
     * @mbg.generated
     */
    private Integer dmpNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_mp.DMP_calorie
     *
     * @mbg.generated
     */
    private Double dmpCalorie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_mp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.DP_id
     *
     * @return the value of day_mp.DP_id
     *
     * @mbg.generated
     */
    public Integer getDpId() {
        return dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.DP_id
     *
     * @param dpId the value for day_mp.DP_id
     *
     * @mbg.generated
     */
    public void setDpId(Integer dpId) {
        this.dpId = dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.M_id
     *
     * @return the value of day_mp.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.M_id
     *
     * @param mId the value for day_mp.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.M_name
     *
     * @return the value of day_mp.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.M_name
     *
     * @param mName the value for day_mp.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.C_id
     *
     * @return the value of day_mp.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.C_id
     *
     * @param cId the value for day_mp.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.DMP_num
     *
     * @return the value of day_mp.DMP_num
     *
     * @mbg.generated
     */
    public Integer getDmpNum() {
        return dmpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.DMP_num
     *
     * @param dmpNum the value for day_mp.DMP_num
     *
     * @mbg.generated
     */
    public void setDmpNum(Integer dmpNum) {
        this.dmpNum = dmpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_mp.DMP_calorie
     *
     * @return the value of day_mp.DMP_calorie
     *
     * @mbg.generated
     */
    public Double getDmpCalorie() {
        return dmpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_mp.DMP_calorie
     *
     * @param dmpCalorie the value for day_mp.DMP_calorie
     *
     * @mbg.generated
     */
    public void setDmpCalorie(Double dmpCalorie) {
        this.dmpCalorie = dmpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_mp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dpId=").append(dpId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", cId=").append(cId);
        sb.append(", dmpNum=").append(dmpNum);
        sb.append(", dmpCalorie=").append(dmpCalorie);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}