package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class DayMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.D_id
     *
     * @mbg.generated
     */
    private Integer dId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.DM_num
     *
     * @mbg.generated
     */
    private Integer dmNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.DM_income
     *
     * @mbg.generated
     */
    private Double dmIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.DM_expand
     *
     * @mbg.generated
     */
    private Double dmExpand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_menu.DM_profit
     *
     * @mbg.generated
     */
    private Double dmProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.D_id
     *
     * @return the value of day_menu.D_id
     *
     * @mbg.generated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.D_id
     *
     * @param dId the value for day_menu.D_id
     *
     * @mbg.generated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.M_id
     *
     * @return the value of day_menu.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.M_id
     *
     * @param mId the value for day_menu.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.M_name
     *
     * @return the value of day_menu.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.M_name
     *
     * @param mName the value for day_menu.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.DM_num
     *
     * @return the value of day_menu.DM_num
     *
     * @mbg.generated
     */
    public Integer getDmNum() {
        return dmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.DM_num
     *
     * @param dmNum the value for day_menu.DM_num
     *
     * @mbg.generated
     */
    public void setDmNum(Integer dmNum) {
        this.dmNum = dmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.DM_income
     *
     * @return the value of day_menu.DM_income
     *
     * @mbg.generated
     */
    public Double getDmIncome() {
        return dmIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.DM_income
     *
     * @param dmIncome the value for day_menu.DM_income
     *
     * @mbg.generated
     */
    public void setDmIncome(Double dmIncome) {
        this.dmIncome = dmIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.DM_expand
     *
     * @return the value of day_menu.DM_expand
     *
     * @mbg.generated
     */
    public Double getDmExpand() {
        return dmExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.DM_expand
     *
     * @param dmExpand the value for day_menu.DM_expand
     *
     * @mbg.generated
     */
    public void setDmExpand(Double dmExpand) {
        this.dmExpand = dmExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_menu.DM_profit
     *
     * @return the value of day_menu.DM_profit
     *
     * @mbg.generated
     */
    public Double getDmProfit() {
        return dmProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_menu.DM_profit
     *
     * @param dmProfit the value for day_menu.DM_profit
     *
     * @mbg.generated
     */
    public void setDmProfit(Double dmProfit) {
        this.dmProfit = dmProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dId=").append(dId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", dmNum=").append(dmNum);
        sb.append(", dmIncome=").append(dmIncome);
        sb.append(", dmExpand=").append(dmExpand);
        sb.append(", dmProfit=").append(dmProfit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}