package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class DayPersonal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_personal.DP_id
     *
     * @mbg.generated
     */
    private Integer dpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_personal.DP_calorie
     *
     * @mbg.generated
     */
    private Double dpCalorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_personal.DP_expend
     *
     * @mbg.generated
     */
    private Double dpExpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table day_personal
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_personal.DP_id
     *
     * @return the value of day_personal.DP_id
     *
     * @mbg.generated
     */
    public Integer getDpId() {
        return dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_personal.DP_id
     *
     * @param dpId the value for day_personal.DP_id
     *
     * @mbg.generated
     */
    public void setDpId(Integer dpId) {
        this.dpId = dpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_personal.DP_calorie
     *
     * @return the value of day_personal.DP_calorie
     *
     * @mbg.generated
     */
    public Double getDpCalorie() {
        return dpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_personal.DP_calorie
     *
     * @param dpCalorie the value for day_personal.DP_calorie
     *
     * @mbg.generated
     */
    public void setDpCalorie(Double dpCalorie) {
        this.dpCalorie = dpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_personal.DP_expend
     *
     * @return the value of day_personal.DP_expend
     *
     * @mbg.generated
     */
    public Double getDpExpend() {
        return dpExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_personal.DP_expend
     *
     * @param dpExpend the value for day_personal.DP_expend
     *
     * @mbg.generated
     */
    public void setDpExpend(Double dpExpend) {
        this.dpExpend = dpExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_personal
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dpId=").append(dpId);
        sb.append(", dpCalorie=").append(dpCalorie);
        sb.append(", dpExpend=").append(dpExpend);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}