package com.elsa.smart_buffet.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.util.Date;

public class Feedback implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.C_id
     *
     * @mbg.generated
     */
    @JsonProperty(value="cumstomerId")
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.F_time
     *
     * @mbg.generated
     */
    @JsonProperty(value = "feedbackTime")
    private Date fTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.F_status
     *
     * @mbg.generated
     */
    @JsonProperty(value = "returnStatu")
    private Integer fStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.FM_time
     *
     * @mbg.generated
     */
    @JsonProperty(value = "returnTime")
    private Date fmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.F_complaint
     *
     * @mbg.generated
     */
    @JsonProperty(value = "feedbackComplaint")
    private String fComplaint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feedback.FM_opinion
     *
     * @mbg.generated
     */
    @JsonProperty(value = "returnOpinion")
    private String fmOpinion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feedback
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.C_id
     *
     * @return the value of feedback.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.C_id
     *
     * @param cId the value for feedback.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.F_time
     *
     * @return the value of feedback.F_time
     *
     * @mbg.generated
     */
    public Date getfTime() {
        return fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.F_time
     *
     * @param fTime the value for feedback.F_time
     *
     * @mbg.generated
     */
    public void setfTime(Date fTime) {
        this.fTime = fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.F_status
     *
     * @return the value of feedback.F_status
     *
     * @mbg.generated
     */
    public Integer getfStatus() {
        return fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.F_status
     *
     * @param fStatus the value for feedback.F_status
     *
     * @mbg.generated
     */
    public void setfStatus(Integer fStatus) {
        this.fStatus = fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.FM_time
     *
     * @return the value of feedback.FM_time
     *
     * @mbg.generated
     */
    public Date getFmTime() {
        return fmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.FM_time
     *
     * @param fmTime the value for feedback.FM_time
     *
     * @mbg.generated
     */
    public void setFmTime(Date fmTime) {
        this.fmTime = fmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.F_complaint
     *
     * @return the value of feedback.F_complaint
     *
     * @mbg.generated
     */
    public String getfComplaint() {
        return fComplaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.F_complaint
     *
     * @param fComplaint the value for feedback.F_complaint
     *
     * @mbg.generated
     */
    public void setfComplaint(String fComplaint) {
        this.fComplaint = fComplaint == null ? null : fComplaint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feedback.FM_opinion
     *
     * @return the value of feedback.FM_opinion
     *
     * @mbg.generated
     */
    public String getFmOpinion() {
        return fmOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feedback.FM_opinion
     *
     * @param fmOpinion the value for feedback.FM_opinion
     *
     * @mbg.generated
     */
    public void setFmOpinion(String fmOpinion) {
        this.fmOpinion = fmOpinion == null ? null : fmOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feedback
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cId=").append(cId);
        sb.append(", fTime=").append(fTime);
        sb.append(", fStatus=").append(fStatus);
        sb.append(", fmTime=").append(fmTime);
        sb.append(", fComplaint=").append(fComplaint);
        sb.append(", fmOpinion=").append(fmOpinion);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}