package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class History implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.C_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.H_history
     *
     * @mbg.generated
     */
    private String hHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.C_id
     *
     * @return the value of history.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.C_id
     *
     * @param cId the value for history.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.H_history
     *
     * @return the value of history.H_history
     *
     * @mbg.generated
     */
    public String gethHistory() {
        return hHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.H_history
     *
     * @param hHistory the value for history.H_history
     *
     * @mbg.generated
     */
    public void sethHistory(String hHistory) {
        this.hHistory = hHistory == null ? null : hHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cId=").append(cId);
        sb.append(", hHistory=").append(hHistory);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}