package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class MenuOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_order.O_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_order.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_order.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_order.MO_num
     *
     * @mbg.generated
     */
    private Integer moNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_order.MO_price
     *
     * @mbg.generated
     */
    private Double moPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_order.O_id
     *
     * @return the value of menu_order.O_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_order.O_id
     *
     * @param oId the value for menu_order.O_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_order.M_id
     *
     * @return the value of menu_order.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_order.M_id
     *
     * @param mId the value for menu_order.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_order.M_name
     *
     * @return the value of menu_order.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_order.M_name
     *
     * @param mName the value for menu_order.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_order.MO_num
     *
     * @return the value of menu_order.MO_num
     *
     * @mbg.generated
     */
    public Integer getMoNum() {
        return moNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_order.MO_num
     *
     * @param moNum the value for menu_order.MO_num
     *
     * @mbg.generated
     */
    public void setMoNum(Integer moNum) {
        this.moNum = moNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_order.MO_price
     *
     * @return the value of menu_order.MO_price
     *
     * @mbg.generated
     */
    public Double getMoPrice() {
        return moPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_order.MO_price
     *
     * @param moPrice the value for menu_order.MO_price
     *
     * @mbg.generated
     */
    public void setMoPrice(Double moPrice) {
        this.moPrice = moPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oId=").append(oId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", moNum=").append(moNum);
        sb.append(", moPrice=").append(moPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}