package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class MonthMp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.MP_id
     *
     * @mbg.generated
     */
    private Integer mpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.C_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.MMP_num
     *
     * @mbg.generated
     */
    private Integer mmpNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_mp.MMP_calorie
     *
     * @mbg.generated
     */
    private Double mmpCalorie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table month_mp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.MP_id
     *
     * @return the value of month_mp.MP_id
     *
     * @mbg.generated
     */
    public Integer getMpId() {
        return mpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.MP_id
     *
     * @param mpId the value for month_mp.MP_id
     *
     * @mbg.generated
     */
    public void setMpId(Integer mpId) {
        this.mpId = mpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.M_id
     *
     * @return the value of month_mp.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.M_id
     *
     * @param mId the value for month_mp.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.M_name
     *
     * @return the value of month_mp.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.M_name
     *
     * @param mName the value for month_mp.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.C_id
     *
     * @return the value of month_mp.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.C_id
     *
     * @param cId the value for month_mp.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.MMP_num
     *
     * @return the value of month_mp.MMP_num
     *
     * @mbg.generated
     */
    public Integer getMmpNum() {
        return mmpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.MMP_num
     *
     * @param mmpNum the value for month_mp.MMP_num
     *
     * @mbg.generated
     */
    public void setMmpNum(Integer mmpNum) {
        this.mmpNum = mmpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_mp.MMP_calorie
     *
     * @return the value of month_mp.MMP_calorie
     *
     * @mbg.generated
     */
    public Double getMmpCalorie() {
        return mmpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_mp.MMP_calorie
     *
     * @param mmpCalorie the value for month_mp.MMP_calorie
     *
     * @mbg.generated
     */
    public void setMmpCalorie(Double mmpCalorie) {
        this.mmpCalorie = mmpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_mp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mpId=").append(mpId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", cId=").append(cId);
        sb.append(", mmpNum=").append(mmpNum);
        sb.append(", mmpCalorie=").append(mmpCalorie);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}