package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class MonthMenu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.MON_id
     *
     * @mbg.generated
     */
    private Integer monId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.MM_num
     *
     * @mbg.generated
     */
    private String mmNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.MM_income
     *
     * @mbg.generated
     */
    private Double mmIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.MM_expand
     *
     * @mbg.generated
     */
    private Double mmExpand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_menu.MM_profit
     *
     * @mbg.generated
     */
    private Double mmProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table month_menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.MON_id
     *
     * @return the value of month_menu.MON_id
     *
     * @mbg.generated
     */
    public Integer getMonId() {
        return monId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.MON_id
     *
     * @param monId the value for month_menu.MON_id
     *
     * @mbg.generated
     */
    public void setMonId(Integer monId) {
        this.monId = monId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.M_id
     *
     * @return the value of month_menu.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.M_id
     *
     * @param mId the value for month_menu.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.M_name
     *
     * @return the value of month_menu.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.M_name
     *
     * @param mName the value for month_menu.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.MM_num
     *
     * @return the value of month_menu.MM_num
     *
     * @mbg.generated
     */
    public String getMmNum() {
        return mmNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.MM_num
     *
     * @param mmNum the value for month_menu.MM_num
     *
     * @mbg.generated
     */
    public void setMmNum(String mmNum) {
        this.mmNum = mmNum == null ? null : mmNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.MM_income
     *
     * @return the value of month_menu.MM_income
     *
     * @mbg.generated
     */
    public Double getMmIncome() {
        return mmIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.MM_income
     *
     * @param mmIncome the value for month_menu.MM_income
     *
     * @mbg.generated
     */
    public void setMmIncome(Double mmIncome) {
        this.mmIncome = mmIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.MM_expand
     *
     * @return the value of month_menu.MM_expand
     *
     * @mbg.generated
     */
    public Double getMmExpand() {
        return mmExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.MM_expand
     *
     * @param mmExpand the value for month_menu.MM_expand
     *
     * @mbg.generated
     */
    public void setMmExpand(Double mmExpand) {
        this.mmExpand = mmExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_menu.MM_profit
     *
     * @return the value of month_menu.MM_profit
     *
     * @mbg.generated
     */
    public Double getMmProfit() {
        return mmProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_menu.MM_profit
     *
     * @param mmProfit the value for month_menu.MM_profit
     *
     * @mbg.generated
     */
    public void setMmProfit(Double mmProfit) {
        this.mmProfit = mmProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", monId=").append(monId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", mmNum=").append(mmNum);
        sb.append(", mmIncome=").append(mmIncome);
        sb.append(", mmExpand=").append(mmExpand);
        sb.append(", mmProfit=").append(mmProfit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}