package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class Month implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month.MON_id
     *
     * @mbg.generated
     */
    private Integer monId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month.MON_income
     *
     * @mbg.generated
     */
    private Double monIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month.MON_expend
     *
     * @mbg.generated
     */
    private Double monExpend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month.MON_profit
     *
     * @mbg.generated
     */
    private Double monProfit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table month
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month.MON_id
     *
     * @return the value of month.MON_id
     *
     * @mbg.generated
     */
    public Integer getMonId() {
        return monId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month.MON_id
     *
     * @param monId the value for month.MON_id
     *
     * @mbg.generated
     */
    public void setMonId(Integer monId) {
        this.monId = monId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month.MON_income
     *
     * @return the value of month.MON_income
     *
     * @mbg.generated
     */
    public Double getMonIncome() {
        return monIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month.MON_income
     *
     * @param monIncome the value for month.MON_income
     *
     * @mbg.generated
     */
    public void setMonIncome(Double monIncome) {
        this.monIncome = monIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month.MON_expend
     *
     * @return the value of month.MON_expend
     *
     * @mbg.generated
     */
    public Double getMonExpend() {
        return monExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month.MON_expend
     *
     * @param monExpend the value for month.MON_expend
     *
     * @mbg.generated
     */
    public void setMonExpend(Double monExpend) {
        this.monExpend = monExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month.MON_profit
     *
     * @return the value of month.MON_profit
     *
     * @mbg.generated
     */
    public Double getMonProfit() {
        return monProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month.MON_profit
     *
     * @param monProfit the value for month.MON_profit
     *
     * @mbg.generated
     */
    public void setMonProfit(Double monProfit) {
        this.monProfit = monProfit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", monId=").append(monId);
        sb.append(", monIncome=").append(monIncome);
        sb.append(", monExpend=").append(monExpend);
        sb.append(", monProfit=").append(monProfit);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}