package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class MonthPersonal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_personal.MP_id
     *
     * @mbg.generated
     */
    private Integer mpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_personal.MP_calorie
     *
     * @mbg.generated
     */
    private Double mpCalorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column month_personal.MP_expend
     *
     * @mbg.generated
     */
    private Double mpExpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table month_personal
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_personal.MP_id
     *
     * @return the value of month_personal.MP_id
     *
     * @mbg.generated
     */
    public Integer getMpId() {
        return mpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_personal.MP_id
     *
     * @param mpId the value for month_personal.MP_id
     *
     * @mbg.generated
     */
    public void setMpId(Integer mpId) {
        this.mpId = mpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_personal.MP_calorie
     *
     * @return the value of month_personal.MP_calorie
     *
     * @mbg.generated
     */
    public Double getMpCalorie() {
        return mpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_personal.MP_calorie
     *
     * @param mpCalorie the value for month_personal.MP_calorie
     *
     * @mbg.generated
     */
    public void setMpCalorie(Double mpCalorie) {
        this.mpCalorie = mpCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column month_personal.MP_expend
     *
     * @return the value of month_personal.MP_expend
     *
     * @mbg.generated
     */
    public Double getMpExpend() {
        return mpExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column month_personal.MP_expend
     *
     * @param mpExpend the value for month_personal.MP_expend
     *
     * @mbg.generated
     */
    public void setMpExpend(Double mpExpend) {
        this.mpExpend = mpExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_personal
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mpId=").append(mpId);
        sb.append(", mpCalorie=").append(mpCalorie);
        sb.append(", mpExpend=").append(mpExpend);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}