package com.elsa.smart_buffet.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.O_id
     *
     * @mbg.generated
     */
  @JsonProperty(value ="orderId")
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.C_id
     *
     * @mbg.generated
     */
    @JsonProperty(value ="comsumerId")
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.O_time
     *
     * @mbg.generated
     */
    @JsonProperty (value="orderTime")
    private Date oTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.O_totalprice
     *
     * @mbg.generated
     */
    @JsonProperty("orderTotalPrice")
    private Double oTotalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.O_status
     *
     * @mbg.generated
     */

    @JsonProperty("status")
    private Integer oStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.O_id
     *
     * @return the value of order.O_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.O_id
     *
     * @param oId the value for order.O_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.C_id
     *
     * @return the value of order.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.C_id
     *
     * @param cId the value for order.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.O_time
     *
     * @return the value of order.O_time
     *
     * @mbg.generated
     */
    public Date getoTime() {
        return oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.O_time
     *
     * @param oTime the value for order.O_time
     *
     * @mbg.generated
     */
    public void setoTime(Date oTime) {
        this.oTime = oTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.O_totalprice
     *
     * @return the value of order.O_totalprice
     *
     * @mbg.generated
     */
    public Double getoTotalprice() {
        return oTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.O_totalprice
     *
     * @param oTotalprice the value for order.O_totalprice
     *
     * @mbg.generated
     */
    public void setoTotalprice(Double oTotalprice) {
        this.oTotalprice = oTotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.O_status
     *
     * @return the value of order.O_status
     *
     * @mbg.generated
     */
    public Integer getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.O_status
     *
     * @param oStatus the value for order.O_status
     *
     * @mbg.generated
     */
    public void setoStatus(Integer oStatus) {
        this.oStatus = oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oId=").append(oId);
        sb.append(", cId=").append(cId);
        sb.append(", oTime=").append(oTime);
        sb.append(", oTotalprice=").append(oTotalprice);
        sb.append(", oStatus=").append(oStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}