package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class Restaurant implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.res_id
     *
     * @mbg.generated
     */
    private Integer resId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.res_name
     *
     * @mbg.generated
     */
    private String resName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.res_address
     *
     * @mbg.generated
     */
    private String resAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.res_opentime
     *
     * @mbg.generated
     */
    private String resOpentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.res_num
     *
     * @mbg.generated
     */
    private Integer resNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table restaurant
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.res_id
     *
     * @return the value of restaurant.res_id
     *
     * @mbg.generated
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.res_id
     *
     * @param resId the value for restaurant.res_id
     *
     * @mbg.generated
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.res_name
     *
     * @return the value of restaurant.res_name
     *
     * @mbg.generated
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.res_name
     *
     * @param resName the value for restaurant.res_name
     *
     * @mbg.generated
     */
    public void setResName(String resName) {
        this.resName = resName == null ? null : resName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.res_address
     *
     * @return the value of restaurant.res_address
     *
     * @mbg.generated
     */
    public String getResAddress() {
        return resAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.res_address
     *
     * @param resAddress the value for restaurant.res_address
     *
     * @mbg.generated
     */
    public void setResAddress(String resAddress) {
        this.resAddress = resAddress == null ? null : resAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.res_opentime
     *
     * @return the value of restaurant.res_opentime
     *
     * @mbg.generated
     */
    public String getResOpentime() {
        return resOpentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.res_opentime
     *
     * @param resOpentime the value for restaurant.res_opentime
     *
     * @mbg.generated
     */
    public void setResOpentime(String resOpentime) {
        this.resOpentime = resOpentime == null ? null : resOpentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.res_num
     *
     * @return the value of restaurant.res_num
     *
     * @mbg.generated
     */
    public Integer getResNum() {
        return resNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.res_num
     *
     * @param resNum the value for restaurant.res_num
     *
     * @mbg.generated
     */
    public void setResNum(Integer resNum) {
        this.resNum = resNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resId=").append(resId);
        sb.append(", resName=").append(resName);
        sb.append(", resAddress=").append(resAddress);
        sb.append(", resOpentime=").append(resOpentime);
        sb.append(", resNum=").append(resNum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}