package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class YearMp implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.YP_id
     *
     * @mbg.generated
     */
    private Integer ypId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.M_id
     *
     * @mbg.generated
     */
    private Integer mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.M_name
     *
     * @mbg.generated
     */
    private String mName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.C_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.YMP_num
     *
     * @mbg.generated
     */
    private Integer ympNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_mp.YMP_calorie
     *
     * @mbg.generated
     */
    private Double ympCalorie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table year_mp
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.YP_id
     *
     * @return the value of year_mp.YP_id
     *
     * @mbg.generated
     */
    public Integer getYpId() {
        return ypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.YP_id
     *
     * @param ypId the value for year_mp.YP_id
     *
     * @mbg.generated
     */
    public void setYpId(Integer ypId) {
        this.ypId = ypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.M_id
     *
     * @return the value of year_mp.M_id
     *
     * @mbg.generated
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.M_id
     *
     * @param mId the value for year_mp.M_id
     *
     * @mbg.generated
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.M_name
     *
     * @return the value of year_mp.M_name
     *
     * @mbg.generated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.M_name
     *
     * @param mName the value for year_mp.M_name
     *
     * @mbg.generated
     */
    public void setmName(String mName) {
        this.mName = mName == null ? null : mName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.C_id
     *
     * @return the value of year_mp.C_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.C_id
     *
     * @param cId the value for year_mp.C_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.YMP_num
     *
     * @return the value of year_mp.YMP_num
     *
     * @mbg.generated
     */
    public Integer getYmpNum() {
        return ympNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.YMP_num
     *
     * @param ympNum the value for year_mp.YMP_num
     *
     * @mbg.generated
     */
    public void setYmpNum(Integer ympNum) {
        this.ympNum = ympNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_mp.YMP_calorie
     *
     * @return the value of year_mp.YMP_calorie
     *
     * @mbg.generated
     */
    public Double getYmpCalorie() {
        return ympCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_mp.YMP_calorie
     *
     * @param ympCalorie the value for year_mp.YMP_calorie
     *
     * @mbg.generated
     */
    public void setYmpCalorie(Double ympCalorie) {
        this.ympCalorie = ympCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_mp
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ypId=").append(ypId);
        sb.append(", mId=").append(mId);
        sb.append(", mName=").append(mName);
        sb.append(", cId=").append(cId);
        sb.append(", ympNum=").append(ympNum);
        sb.append(", ympCalorie=").append(ympCalorie);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}