package com.elsa.smart_buffet.pojo;

import java.io.Serializable;

public class YearPersonal implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_personal.YP_id
     *
     * @mbg.generated
     */
    private Integer ypId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_personal.YP_calorie
     *
     * @mbg.generated
     */
    private Double ypCalorie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column year_personal.YP_expend
     *
     * @mbg.generated
     */
    private Double ypExpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table year_personal
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_personal.YP_id
     *
     * @return the value of year_personal.YP_id
     *
     * @mbg.generated
     */
    public Integer getYpId() {
        return ypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_personal.YP_id
     *
     * @param ypId the value for year_personal.YP_id
     *
     * @mbg.generated
     */
    public void setYpId(Integer ypId) {
        this.ypId = ypId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_personal.YP_calorie
     *
     * @return the value of year_personal.YP_calorie
     *
     * @mbg.generated
     */
    public Double getYpCalorie() {
        return ypCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_personal.YP_calorie
     *
     * @param ypCalorie the value for year_personal.YP_calorie
     *
     * @mbg.generated
     */
    public void setYpCalorie(Double ypCalorie) {
        this.ypCalorie = ypCalorie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column year_personal.YP_expend
     *
     * @return the value of year_personal.YP_expend
     *
     * @mbg.generated
     */
    public Double getYpExpend() {
        return ypExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column year_personal.YP_expend
     *
     * @param ypExpend the value for year_personal.YP_expend
     *
     * @mbg.generated
     */
    public void setYpExpend(Double ypExpend) {
        this.ypExpend = ypExpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table year_personal
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ypId=").append(ypId);
        sb.append(", ypCalorie=").append(ypCalorie);
        sb.append(", ypExpend=").append(ypExpend);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}